#
# Module manifest for module 'IdentityManager'
#
# Generated by: Rob Looman
#
# Generated on: 29-10-2020
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'IdentityManager.psm1'

# Version number of this module.
ModuleVersion = '3.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'dbdb3c70-b458-4ff6-966b-bda47bd29963'

# Author of this module
Author = 'Rob Looman'

# Company or vendor of this module
CompanyName = 'IAM Security'

# Copyright statement for this module
Copyright = '(c) Rob Looman. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Powershell Module for accessing One Identity'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()


# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    #Main
    "New-OIMSession",
    "Close-OIMSession",
    "Get-OIMObject",
    "Get-OIMURI",
    "New-OIMObject",
    "Remove-OIMObject",
    "Add-OIMObjectMember",
    "Remove-OIMObjectMember",
    "Set-OIMConfigParameter",
    "Set-OIMGlobalVariable",
    "Start-OIMSchedule",
    "Set-OIMObject",
    "Wait-OIMJobQueue",
    "Wait-OIMObject",
    #BusinessLayer
    "Get-OIMPerson",
    "Get-OIMEset",
    "Get-OIMUNSAccountB",
    "Get-OIMUNSGroupB",
    "Get-OIMUNSAccountBInUNSGroupB",
    "Add-OIMPersonHasEset",
    #CMD
    "Install-OIMTransportFiles",
    "Start-OIMScript",
    "Start-OIMMethod",
    "Start-OIMEvent",
    "Start-OIMScript",
    "Start-OIMSyncProject",
    #Get
    "Get-OIMUNSAccountB",
    "Get-OIMTSBAccountDef",
    "Get-OIMPersonHasTSBAccountDef",
    "Get-OIMESet",
    "Get-OIMPersonHasESet",
    #New
    "New-OIMPerson",
    "New-OIMPersonHasEset",
    #SQL
    "Connect-OIMSQL",
    "Invoke-OIMSQLQuery",
    "Invoke-DBCompiler",
    #
    "Install-OIMFunction" )

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @("One Identity","Identity Manager")

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

